kind: pipeline
type: docker
name: moneybags-server

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone --single-branch --branch $DRONE_SOURCE_BRANCH --depth=1 $DRONE_GIT_HTTP_URL .

  - name: test
    image: golang:1.16
    commands:
      - go install github.com/golang/mock/mockgen@v1.6.0
      - make test

  - name: build
    image: golang:1.16
    commands:
      - make build

  - name: publish-dev
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: paulwrubel/moneybags-server
      tags:
        - dev
        - ${DRONE_COMMIT_SHA:0:7}
    when:
      branch:
        - main
      event:
        - push

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: paulwrubel/moneybags-server
      tags:
        - latest
        - ${DRONE_TAG##v}
    when:
      event:
        - tag
